package com.example.thuchanh2;

public class DescriptionPlace {
//        String[] cars = { "Honda", "BMW", "Ford", "Mazda" };
public static String[] locationn(){
    String hoguom = "Hồ Hoàn Kiếm (chữ Nôm: 湖還劍 hoặc 還劍湖) còn được gọi là Hồ Gươm là một hồ nước ngọt tự nhiên nằm ở trung tâm thành phố Hà Nội. Hồ có diện tích khoảng 12 ha[2]. Trước kia, hồ còn có các tên gọi là hồ Lục Thủy (vì nước có màu xanh quanh năm), hồ Thủy Quân (dùng để duyệt thủy binh), hồ Tả Vọng và Hữu Vọng (trong thời Lê mạt). Tên gọi Hoàn Kiếm xuất hiện vào đầu thế kỷ 15 gắn với truyền thuyết vua Lê Lợi trả lại gươm thần cho Rùa thần. Theo truyền thuyết, trong một lần vua Lê Thái Tổ dạo chơi trên thuyền, bỗng một con rùa vàng nổi lên mặt nước đòi nhà vua trả thanh gươm mà Long Vương cho mượn để đánh đuổi quân Minh xâm lược. Nhà vua liền trả gươm cho rùa thần và rùa lặn xuống nước biến mất. Từ đó hồ được lấy tên là hồ Hoàn Kiếm. Tên hồ còn được lấy để đặt cho một quận trung tâm của Hà Nội (quận Hoàn Kiếm) và là hồ nước duy nhất của quận này cho đến ngày nay.\n" +
            "\n" +
            "Hồ Hoàn Kiếm có vị trí kết nối giữa khu phố cổ gồm các phố Hàng Ngang, Hàng Đào, Cầu Gỗ, Lương Văn Can, Lò Sũ... với khu phố Tây do người Pháp quy hoạch cách đây hơn một thế kỷ là Bảo Khánh, Nhà thờ, Tràng Thi, Hàng Bài, Đinh Tiên Hoàng, Tràng Tiền, Hàng Khay, Bà Triệu.";
    String langchutich = "Lăng Chủ tịch Hồ Chí Minh, còn gọi là Lăng Hồ Chủ tịch, Lăng Bác, là nơi gìn giữ di hài Chủ tịch Hồ Chí Minh. Lăng được chính thức khởi công ngày 2 tháng 9 năm 1973, tại vị trí của lễ đài cũ giữa Quảng trường Ba Đình, nơi Hồ Chí Minh từng chủ trì các cuộc gặp mặt quan trọng.\n" +
            "\n" +
            "Lăng được khánh thành vào ngày 29 tháng 8 năm 1975, gồm 3 lớp với chiều cao 21,6 mét, chiều rộng 41,2 mét lớp dưới tạo dáng bậc thềm tam cấp, lớp giữa là kết cấu trung tâm của lăng gồm phòng thi hài và những hành lang, những cầu thang. Bên ngoài lăng được ốp bằng đá granite xám, bên trong làm bằng đá xám và đỏ đã được đánh bóng. Quanh bốn mặt là những hàng cột vuông bằng đá hoa cương, lớp trên cùng là mái lăng hình tam cấp. Ở mặt chính có dòng chữ: \"CHỦ TỊCH HỒ-CHÍ-MINH\" bằng đá hồng màu mận chín. Xung quanh lăng là các khu vườn nơi hơn 250 loài thực vật được trồng từ khắp mọi miền của Việt Nam.\n" +
            "\n" +
            "Trong di chúc, Chủ tịch Hồ Chí Minh muốn được hỏa táng và đặt tro tại ba miền đất nước.[1] Tuy nhiên, Bộ Chính trị Ban Chấp hành Trung ương Đảng Cộng sản Việt Nam khóa III, với lý do tuân theo nguyện vọng và tình cảm của nhân dân, quyết định giữ gìn lâu dài thi hài chủ tịch Hồ Chí Minh để sau này người dân cả nước, nhất là người dân miền Nam, khách quốc tế có thể tới viếng.";
    String cotcohanoi = "Cột cờ Hà Nội hay còn gọi Kỳ đài Hà Nội là một kết cấu dạng tháp được xây dựng cùng thời với thành Hà Nội dưới triều nhà Nguyễn (bắt đầu năm 1805, hoàn thành năm 1812). Kiến trúc cột cờ bao gồm ba tầng đế và một thân cột, được coi là một trong những biểu tượng của thành phố.";
    String chuamotcot = "Chùa Một Cột có tên ban đầu là Liên Hoa Đài (蓮花臺)[1][2][3] tức là Đài Hoa Sen với lối kiến trúc độc đáo: một điện thờ đặt trên một cột trụ duy nhất. Liên Hoa Đài là công trình nổi tiếng nhất nằm trong quần thể kiến trúc Chùa Diên Hựu (延祐寺)[1][4], có nghĩa là ngôi chùa \"Phúc lành dài lâu\". Công trình Chùa Diên Hựu nguyên bản được xây vào thời vua Lý Thái Tông mùa đông năm 1049[5] và hoàn thiện vào năm 1105 thời vua Lý Nhân Tông[6] nay đã không còn. Công trình Liên Hoa Đài hiện tại nằm ở Hà Nội là một phiên bản được chỉnh sửa nhiều lần qua các thời kỳ, bị Pháp phá huỷ khi rút khỏi Hà Nội ngày 11/9/1954[7][8][9][10] và được dựng lại năm 1955 bởi kiến trúc sư Nguyễn Bá Lăng theo kiến trúc để lại từ thời Nguyễn. Đây là ngôi chùa có kiến trúc độc đáo ở Việt Nam.";
    String hotay = "Hồ Tây (với các tên gọi khác trong lịch sử như Đầm Xác Cáo, Hồ Kim Ngưu, Lãng Bạc, Dâm Đàm, Đoài Hồ) là hồ tự nhiên lớn nhất thành phố Hà Nội, hiện thuộc địa phận quận Tây Hồ. Đây là một hồ móng ngựa và là vết tích của dòng chảy cũ của sông Hồng. Hồ có diện tích hơn 500 ha với chu vi là khoảng 14,8 km.[2]";
    String chuatranquoc = "Chùa Trấn Quốc (鎮國寺) nằm trên một hòn đảo phía Đông Hồ Tây (quận Tây Hồ), chùa có lịch sử gần 1500 năm, được coi là lâu đời nhất ở Thăng Long - Hà Nội. Kiến trúc chùa có sự kết hợp hài hoà giữa tính uy nghiêm, cổ kính với cảnh quan thanh nhã giữa nền tĩnh lặng của một hồ nước mênh mang. Là trung tâm Phật giáo của kinh thành Thăng Long vào thời nhà Lý và nhà Trần. Với những giá trị về lịch sử và kiến trúc, chùa Trấn Quốc nổi tiếng là chốn cửa Phật linh thiêng, là điểm thu hút rất nhiều tín đồ Phật tử và khách tham quan, du lịch trong ngoài Việt Nam.";
    String[] location = {hoguom,langchutich,cotcohanoi,chuamotcot,hotay,chuatranquoc};
    return location;
    }
}
